// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package stores

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64        `json:"id"`
	Uid       interface{}  `json:"uid"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
